run_web:
  port: 8501
  start_web: false
  sidebar:
    sidebar_name: "Streamlit"
  image_list:
    image_list_file:
      - ""
    columns: ['path', ]
    default_index: 0
  model_cfg:
    register_modules:
      - test
    name: test
  mode:
    - run_web
  run_web:
    test: test



